import { Inter } from "next/font/google";
import "./globals.css";
import 'primereact/resources/primereact.css'
import { AuthProvider } from "@/components/AuthContext/AuthProvider";
import { PrimeReactProvider} from 'primereact/api';
import React from 'react';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';  
import 'primereact/resources/primereact.css';
import 'primereact/resources/themes/lara-light-indigo/theme.css';

import { ErrorBoundary } from "react-error-boundary";
import ErrorComponent from "@/errorHandling/ErrorComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BITES Bank",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ErrorBoundary
        FallbackComponent={ErrorComponent}>
        <PrimeReactProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </PrimeReactProvider>
        </ErrorBoundary>

      </body>
    </html>
  );
}
